quarkus.openapi-generator.codegen.spec.reproducer_retry_json.base-package=org.acme.reproducer
quarkus.openapi-generator.codegen.spec.reproducer_retry_json.mutiny=true
quarkus.rest-client.reproducer_retry_json.url=http://localhost:8081/
quarkus.openapi-generator.reproducer_retry_json.auth.AccessTokenHeader.bearer-token=test-token
